import type { DatabaseSync, SQLOutputValue } from 'node:sqlite';
import type { Store } from '../store.js';
import { z } from 'zod';
import { EventStore } from '../events/event-store.js';
import type { ServiceOwnership } from './ownership.js';

export type RecoveryClass =
  'safe-to-continue' | 'safe-to-observe' | 'manual-reconciliation' | 'terminal';
export interface RecoveryRecord {
  table: string;
  id: string;
  state: string;
  classification: RecoveryClass;
  reason: string;
}
interface RecoverySource {
  table: string;
  id?: string;
  state?: string;
  terminal: readonly string[];
  local: readonly string[];
  locator?: string;
}
const sources: readonly RecoverySource[] = [
  {
    table: 'attempts',
    state: 'phase',
    terminal: ['settled', 'closed'],
    local: ['pending'],
    locator: 'native_locator',
  },
  {
    table: 'native_attempts',
    id: 'attempt_id',
    state: 'phase',
    terminal: ['settled'],
    local: ['admitted'],
    locator: 'identity_json',
  },
  { table: 'native_effects', state: 'effect_kind', terminal: [], local: [] },
  { table: 'notification_deliveries', terminal: ['acknowledged'], local: ['pending'] },
  {
    table: 'handoffs',
    terminal: ['integrated', 'retained', 'abandoned'],
    local: ['pending'],
    locator: 'actual_target_state_json',
  },
  { table: 'handoff_claims', terminal: ['settled'], local: [] },
  { table: 'workspace_retirements', terminal: ['completed'], local: ['pending'] },
  { table: 'attempt_control_intents', terminal: ['confirmed'], local: [] },
  { table: 'native_approvals', terminal: ['resolved', 'obsolete'], local: [] },
  { table: 'execution_reservations', terminal: ['released'], local: [] },
  { table: 'writer_reservations', terminal: ['released'], local: [] },
  {
    table: 'controller_incarnations',
    id: 'controller_id',
    terminal: ['settled', 'superseded'],
    local: [],
    locator: 'native_identity_json',
  },
  {
    table: 'controller_inbox_items',
    terminal: ['acknowledged', 'superseded', 'dead-letter'],
    local: ['pending'],
  },
  { table: 'cross_project_outbox', terminal: ['acknowledged', 'rejected'], local: ['pending'] },
  {
    table: 'cross_project_inbox',
    terminal: ['processed', 'rejected', 'acknowledged'],
    local: ['pending'],
  },
  { table: 'budget_reservations', terminal: ['released', 'settled'], local: [] },
  {
    table: 'exact_native_approvals',
    terminal: ['resolved', 'rejected', 'obsolete'],
    local: [],
    locator: 'operation_id',
  },
  { table: 'service_action_claims', terminal: ['completed'], local: [] },
  { table: 'controller_native_effects', terminal: ['settled'], local: [] },
  { table: 'workflow_schedule_intents', terminal: ['admitted', 'superseded'], local: ['pending'] },
  {
    table: 'workflow_attempt_deadlines',
    id: 'attempt_id',
    terminal: ['settled'],
    local: ['pending'],
  },
];

function classify(
  db: DatabaseSync,
  source: RecoverySource,
  row: Record<string, SQLOutputValue>,
): RecoveryRecord {
  const state = z.string().parse(row[source.state ?? 'state']);
  const id =
    String(row[source.id ?? 'id'] ?? row.recovery_rowid) +
    (source.table === 'controller_incarnations' ? ':' + String(row.generation) : '');
  let classification: RecoveryClass = 'manual-reconciliation';
  let reason =
    'An external effect or reservation may exist; reconcile exact evidence before further mutation.';
  if (source.terminal.includes(state)) {
    classification = 'terminal';
    reason = 'Durable settlement or acknowledgement exists.';
  } else if (source.local.includes(state)) {
    classification = 'safe-to-continue';
    reason = 'Local pending intent; admission must still validate current authority and revisions.';
  } else if (source.locator && row[source.locator]) {
    classification = 'safe-to-observe';
    reason =
      'Persisted locator permits read-only reconciliation; positively match full native identity.';
  }
  if (source.table === 'native_effects') {
    const native = db
      .prepare('SELECT phase,identity_json FROM native_attempts WHERE attempt_id=?')
      .get(row.attempt_id!);
    if (native?.phase === 'settled') {
      classification = 'terminal';
      reason = 'Associated native attempt has durable settlement.';
    } else if (native?.identity_json) {
      classification = 'safe-to-observe';
      reason = 'Associated native attempt has persisted exact identity; never repeat the effect.';
    }
  }
  return { table: source.table, id, state, classification, reason };
}
/** Snapshot high-water marks avoid recursively classifying events generated by recovery itself. */
function* recoveryPages(store: Store, pageSize: number): Generator<RecoveryRecord[]> {
  const snapshots = store.read((db) =>
    sources.flatMap((source) => {
      if (
        !db
          .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?")
          .get(source.table)
      )
        return [];
      const columns = db
        .prepare(`PRAGMA table_info(${source.table})`)
        .all()
        .map((row) => z.string().parse(row.name));
      if (!columns.includes(source.state ?? 'state'))
        throw new Error(`Recovery source ${source.table} lacks state column`);
      const scoped = columns.includes('project_id');
      const max = Number(
        db.prepare(`SELECT COALESCE(MAX(rowid),0) AS n FROM ${source.table}`).get()?.n,
      );
      return [{ source, scoped, max }];
    }),
  );
  for (const { source, scoped, max } of snapshots) {
    let after = 0;
    for (;;) {
      const page = store.read((db) => {
        const query = `SELECT rowid AS recovery_rowid,* FROM ${source.table} WHERE rowid>? AND rowid<=? ${scoped ? 'AND project_id=?' : ''} ORDER BY rowid LIMIT ?`;
        const rows = scoped
          ? db.prepare(query).all(after, max, store.project.id, pageSize)
          : db.prepare(query).all(after, max, pageSize);
        return {
          last: rows.length ? Number(rows[rows.length - 1]!.recovery_rowid) : after,
          records: rows.map((row) => classify(db, source, row)),
        };
      });
      if (!page.records.length) break;
      after = page.last;
      yield page.records;
    }
  }
}
/** Classification never releases reservations or retries effects. Public inspection is bounded. */
export function scanRecovery(store: Store, limit = 500): RecoveryRecord[] {
  z.number().int().min(1).max(10000).parse(limit);
  const records: RecoveryRecord[] = [];
  for (const page of recoveryPages(store, Math.min(limit, 100))) {
    records.push(...page.slice(0, limit - records.length));
    if (records.length === limit) break;
  }
  return records;
}

export type RecoveryObserver = (record: RecoveryRecord) => Promise<void>;
export class RecoveryRegistry {
  readonly #observers = new Map<string, RecoveryObserver>();
  register(table: string, observer: RecoveryObserver) {
    if (this.#observers.has(table))
      throw new Error(`Recovery observer already registered: ${table}`);
    this.#observers.set(table, observer);
    return this;
  }
  async recover(owner: ServiceOwnership): Promise<readonly RecoveryRecord[]> {
    const records: RecoveryRecord[] = [];
    const events = new EventStore(owner.store);
    for (const page of recoveryPages(owner.store, 100)) {
      owner.heartbeat('recovering');
      for (const record of page) {
        records.push(record);
        owner.store.transaction((db) => {
          owner.assertCurrent(db);
          events.append({
            kind: 'recovery.classified',
            aggregate: { kind: record.table, id: record.id, revision: 1 },
            payload: record,
            dedupeKey: `recovery:${owner.generation}:${record.table}:${record.id}:${record.state}`,
          });
        });
        if (record.classification === 'safe-to-observe') {
          const observer = this.#observers.get(record.table);
          if (observer) {
            owner.store.read((db) => owner.assertCurrent(db));
            await observer(record);
          }
        }
      }
      await new Promise<void>((resolve) => setImmediate(resolve));
    }
    return records;
  }
}
