import { configurationHelp } from './configuration-cli.js';

export const cliCommands = {
  setup: 'Guided project setup; new projects use Herdr default',
  init: 'Alias for setup',
  lead: 'Reconnect to the existing lead or launch it; --print prints instructions',
  profiles: 'List, discover, set, remove, validate and choose default model profiles',
  roles: 'List, set and remove project roles or instance defaults',
  authorize: 'Record scoped user authority for an outcome',
  update: 'Update CLI and shared supervisor while preserving lead conversations',
  upgrade: 'Alias for update',
  remove: 'Remove this project from Marionette',
  uninstall: 'Remove the instance; --global also removes the CLI',
  start: 'Start the persistent supervisor',
  serve: 'Run the supervisor in the foreground',
  stop: 'Stop the supervisor; workers survive',
  dashboard: 'Print the private dashboard access link',
  'mcp-config': 'Print the MCP configuration',
  projects: 'List connected projects',
  briefing: 'Read project assignments, lead, decisions and questions',
  inbox: 'Read durable notifications',
  doctor: 'Inspect configured connections',
  call: 'Call any action listed below with JSON input',
  'worker-report': 'Submit a scoped report from a worker pane',
  'worker-call': 'Call within worker scope',
  'worker-mcp': 'Internal: serve the scoped worker MCP bridge',
  'guard-hook': 'Internal: validate a harness hook',
  version: 'Print the installed version (also --version)',
  help: 'Show all commands and actions (also --help or -h)',
};

export const cliActions = [
  'adapter.capabilities',
  'authority.get',
  'authority.grant',
  'board.get',
  'checkpoint.get',
  'checkpoint.save',
  'cleanup.archive',
  'cleanup.collect',
  'cleanup.configure',
  'cleanup.deliver',
  'cleanup.preview',
  'cleanup.reconcile',
  'cleanup.release',
  'decision.record',
  'inbox.ack',
  'inbox.read',
  'lead.acquire',
  'lead.handover',
  'lead.wait',
  'lead.wait-ack',
  'lead.wait-reconcile',
  'lead.waits',
  'limits.configure',
  'outcome.assess',
  'outcome.complete',
  'outcome.create',
  'outcome.get',
  'outcome.integrate',
  'outcome.list',
  'outcome.revise',
  'plan.get',
  'plan.revise',
  'profile.configure',
  'profile.discover',
  'profile.validate',
  'project.briefing',
  'project.configure',
  'project.inspect',
  'project.list',
  'project.reconnect',
  'project.register',
  'role.configure',
  'role.list',
  'strategy.advance',
  'strategy.contribute',
  'strategy.create',
  'strategy.finish',
  'strategy.reopen',
  'swarm.capacity.configure',
  'swarm.capacity.feedback',
  'swarm.decision.open',
  'swarm.decision.resolve',
  'swarm.delivery.configure',
  'swarm.dispatch',
  'swarm.evaluation.record',
  'swarm.experiment.compare',
  'swarm.experiment.create',
  'swarm.experiment.select',
  'swarm.intent.amend',
  'swarm.intent.get',
  'swarm.message.send',
  'swarm.observe',
  'swarm.ownership.transfer',
  'swarm.recipe.get',
  'swarm.trajectory',
  'swarm.watch.ack',
  'swarm.watch.cancel',
  'swarm.watch.create',
  'task.control',
  'task.get',
  'task.reconcile',
  'task.retry',
  'task.submit',
  'usage.import',
];

export function commandHelp(command: string) {
  if (command === 'profiles' || command === 'roles') return configurationHelp[command];
  const usage = {
    start: '[--home DIR] [--port NUMBER]',
    serve: '[--home DIR] [--port NUMBER]',
    stop: '[--home DIR]',
    dashboard: '[--home DIR]',
    'mcp-config': '[--home DIR]',
    projects: '[--home DIR]',
    doctor: '[--home DIR]',
    briefing: 'PROJECT_ID [--home DIR]',
    inbox: 'PROJECT_ID [--consumer NAME] [--home DIR]',
    call: 'ACTION [--file JSON_FILE | --json JSON] [--lease FILE] [--save-lease FILE] [--home DIR]',
    'worker-report': '--file JSON_FILE',
    'worker-call': '--file JSON_FILE',
    'worker-mcp': '',
    'guard-hook': '--policy FILE < hook.json',
    version: '',
  };
  return `Usage: marionette ${command} ${Object.entries(usage).find(([name]) => name === command)?.[1] ?? '--help'}\n${Object.entries(cliCommands).find(([name]) => name === command)?.[1]}`;
}
export function fullHelp() {
  return (
    'Marionette — one project, many workers\n\nUsage: marionette <command> [options]\n\n' +
    Object.entries(cliCommands)
      .map(([name, description]) => `  ${name.padEnd(15)} ${description}`)
      .join('\n') +
    '\n\nRun marionette <command> --help for options.\n\nAll call actions:\n' +
    cliActions.map((action) => '  ' + action).join('\n') +
    '\n'
  );
}
